name: "Build Android app"

on:
  push:
  pull_request: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node  
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: Run Yarn Install
        run:  yarn install

      - name: Make gradlew executable
        run: |
            cd android
            chmod +x ./gradlew
            cd ..
                         
      - name: Build application
        run: |
             cd android
             ./gradlew clean
             ./gradlew assembleDebug
             cd ..